import os

GDRIVE_FOLDER_ID = os.environ.get("GDRIVE_FOLDER_ID", "")
REFRESH_TOKEN = os.environ.get("GOOGLE_REFRESH_TOKEN", "")
CLIENT_SECRET_JSON = os.environ.get("GOOGLE_CLIENT_SECRET_JSON", "")

CHANNEL_NAME = "Club BGM"
NUM_SONGS = 5
TARGET_HOURS = 3

VIDEO_WIDTH = 1920
VIDEO_HEIGHT = 1080
VIDEO_FPS = 30

WORK_DIR = "work"
PLAYLIST_ID = "PLScjgbej40yio7exgjBSvFWmV5HOJSHlB"
